config/routes.rb
Rails.application.routes.draw do
  
  root "application#index"

  resources :sites

end

app/models/site.rb
class Site < ActiveRecord::Base

def version
  # document = Nokogiri::XML(open(self.url))
  # releases = document.xpath("//release", "xmlns" => "http://purl.org/dc/elements/1.1/")
  # return releases[0].xpath('version').inner_text
  text = open(self.url) { |io| io.read }
  version = text.split(",").first.split(" ")
  return version[1]
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_version

  require 'open-uri'

  def index
    @current = current_version
  end

  def current_version
    document = Nokogiri::XML(open("http://updates.drupal.org/release-history/drupal/7.x"))
    # Load the data from the XML file into a variable

    releases = document.xpath("//release", "xmlns" => "http://purl.org/dc/elements/1.1/")
    # Creates an array of all the releases specified in the document

    @current_version = releases[0].xpath('version').inner_text
    # Set's the current_version to the version number of the first release in the file. Asssumed to be the most recent. 

    @security_release
    # Declare an instance variable for security_release

    releases.each do |r|
      # Iterate through the releases

      if !@security_release.blank?
        break
      end
      # If the security release has been specified, end the iteration of releases as it's no longer needed.

      version = r.xpath('version').inner_text
      # Store the version number of the current release

      r.xpath("//term", "xmlns" => "http://purl.org/dc/elements/1.1/").each do |t|
        # Iterate through this releases terms

        if @security_release.blank?
          # If the security release hasn't been specified yet, continue.

          if t.children[1].inner_text.downcase == "security update"
            # If the 'value' of the current term is "Security Update"

            @security_release = version
            # Set the value of "security_release" with the version numbero of the current release

          end
        end
      end
    end 

  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

def index
  @sites = Site.all
end

def new
  @site = Site.new
end

def create
  @site = Site.create(site_params)
  redirect_to @site
end

def show
  @site = Site.find(params[:id])
end

def edit
  @site = Site.find(params[:id])
end

def update
  @site = Site.find(params[:id])
  @site.update(site_params)
  redirect_to @site
end

def destroy
  s = Site.find(params[:id])
  s.destroy
  redirect_to sites_path
end

private

  def site_params (params = self.params)
    params.require(:site).permit(:name, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/application/index.html.haml
%h1
  Current Version:
  = @current_version
%h1
  Security Release:
  = @security_release
%p
  Based on latest release @ http://updates.drupal.org/release-history/drupal/7.x
%p
  = link_to "Sites", sites_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DrupalVersionChecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/edit.html.haml
%h1 Edit Site

= form_for @site do |f|
  %table
    %tr
      %td= f.label :name, "Site name"
      %td= f.text_field :name, size: 40
    %tr
      %td= f.label :url, "XML URL"
      %td= f.text_field :url, size: 60
    %tr
      %td
      %td= f.submit "Save"

app/views/sites/index.html.haml
%h1 Sites

- if @sites.count > 0
  %table
    %tr
      %th Site Name
      %th URL
      %th Drupal Version
      %th Up to date?
    - @sites.each do |s|
      - version = s.version
      %tr
        %td= link_to s.name, s
        %td= s.url
        %td= version
        %td= @current_version != version ? "NO" : "YES"

- else
  %p No sites to display. 

= link_to "Add new site", new_site_path

app/views/sites/new.html.haml
%h1 New Site

= form_for @site do |f|
  %table
    %tr
      %td= f.label :name, "Site name"
      %td= f.text_field :name, size: 40
    %tr
      %td= f.label :url, "XML URL"
      %td= f.text_field :url, size: 60
    %tr
      %td
      %td= f.submit "Save"

app/views/sites/show.html.haml
%h1 View Site

%p= "Name: #{@site.name}"
%p= "URL: #{@site.url}"
%p= "Drupal Version: #{@site.version}"

%p= link_to "Edit", edit_site_path(@site)

%p= link_to "Delete Site", @site, :method => :delete